#!/bin/bash
#
# Phillips webcam module setup WITHOUT the pwcx-i386 compressor
#
# Copyright (c) 2000-2003 by Landon Curt Noll and Simon Cooper.
# All Rights Reserved.
#
# This is open software; you can redistribute it and/or modify it under
# the terms of the version 2.1 of the GNU Lesser General Public License
# as published by the Free Software Foundation.
#
# This software is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General
# Public License for more details.
#
# The file COPYING contains important info about Licenses and Copyrights.
# Please read the COPYING file for details about this open software.
#
# A copy of version 2.1 of the GNU Lesser General Public License is
# distributed with calc under the filename COPYING-LGPL.  You should have
# received a copy with calc; if not, write to Free Software Foundation, Inc.
# 59 Temple Place, Suite 330, Boston, MA  02111-1307, USA.
#
# For more information on LavaRnd: http://www.LavaRnd.org
#
# Share and enjoy! :-)

# setup
#
LAVARND_VIDEODEV=/dev/video0
LAVARND_USER=lava
LAVARND_GROUP=lava
/usr/bin/logger -p daemon.notice -t hotplug/usb/pwc -i begin pwc setup

# NOTE:
#
# The pwcx-i386 optional binary-only kernel modules, while useful for people
# to get those 640x480 image sizes, does not improve the camera as an
# entropy source.  In some cases it reduces entropy ... although not
# critically.  On the other hand if the lavapool daemon is using your
# camera, you cannot (camera are opened exclusive to a single process)
# so we might as well force the pwcx-i386 module to be removed.
#
# You might want to load the pwcx-i386 module later on if you want
# to view larger frame sizes.  Replace the rmmod line below with:
#
#  if [ -f /etc/hotplug/usb/pwcx-i386.o ]; then
#     /usr/bin/logger -p daemon.notice -t hotplug/usb/pwc -i pwcx-i386.o insmod
#     /sbin/insmod --force /etc/hotplug/usb/pwcx-i386.o >/dev/null 2>&1
#  fi
#
# ... assumng you have the pwcx-i386.o module in the first place!
#
/sbin/rmmod pwcx-i386 >/dev/null 2>&1

# remove the pwc module in case it was setup before with other flags
#
MODULE="`/sbin/lsmod 2>/dev/null | /bin/grep '^pwc[ 	]' 2>/dev/null`"
if [ -n "$MODULE" ]; then
    /sbin/rmmod pwc >/dev/null 2>&1
fi

# start pwc with LavaRnd optimal flags
#
/sbin/modprobe pwc size=vga fps=15 leds=250,750 fbufs=2 mbufs=1 compression=0

# setup video device permissions
#
/bin/chown ${LAVARND_USER}.${LAVARND_GROUP} ${LAVARND_VIDEODEV}
/bin/chmod 0660 ${LAVARND_VIDEODEV}

# tell the world what we did
#
MODULE="`/sbin/lsmod 2>/dev/null | /bin/grep '^pwc[ 	]' 2>/dev/null`"
if [ -n "$MODULE" ]; then
    /usr/bin/logger -p daemon.notice -t hotplug/usb/pwc -i pwc setup complete
else
    /usr/bin/logger -p daemon.notice -t hotplug/usb/pwc -i pwc setup failed
    exit 1
fi
exit 0
