/*
 * randomvideo.c - V4L2-based video capture for LavaRnd entropy source.
 *
 * This function captures a single frame from a webcam using V4L2 and copies
 * the raw data into the provided buffer for use as random entropy.
 * Based on standard V4L2 capture examples, adapted for LavaRnd.
 *
 * Compile as part of LavaRnd; no extra libs needed.
 * Generated by Grok 4 on July 10, 2025 https://x.com/i/grok?conversation=1943297454465523894
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <fcntl.h>
#include <errno.h>
#include <unistd.h>
#include <sys/ioctl.h>
#include <sys/mman.h>
#include <linux/videodev2.h>

#define DEFAULT_DEVICE "/dev/video0"
#define DEFAULT_WIDTH 640
#define DEFAULT_HEIGHT 480
#define DEFAULT_PIXEL_FORMAT V4L2_PIX_FMT_YUYV  // Common for webcams; raw, uncompressed.

size_t randomvideo(unsigned char *buf, size_t len) {
    int fd;
    struct v4l2_capability cap;
    struct v4l2_format fmt;
    struct v4l2_requestbuffers req;
    struct v4l2_buffer vbuf;
    void *frame_buf = NULL;
    size_t captured_bytes = 0;

    // Open the video device.
    fd = open(DEFAULT_DEVICE, O_RDWR);
    if (fd == -1) {
        perror("Failed to open video device");
        return 0;
    }

    // Query device capabilities.
    memset(&cap, 0, sizeof(cap));
    if (ioctl(fd, VIDIOC_QUERYCAP, &cap) == -1) {
        perror("Failed to query capabilities");
        goto cleanup;
    }
    if (!(cap.capabilities & V4L2_CAP_VIDEO_CAPTURE)) {
        fprintf(stderr, "Device does not support video capture\n");
        goto cleanup;
    }
    if (!(cap.capabilities & V4L2_CAP_STREAMING)) {
        fprintf(stderr, "Device does not support streaming I/O\n");
        goto cleanup;
    }

    // Set the frame format.
    memset(&fmt, 0, sizeof(fmt));
    fmt.type = V4L2_BUF_TYPE_VIDEO_CAPTURE;
    fmt.fmt.pix.width = DEFAULT_WIDTH;
    fmt.fmt.pix.height = DEFAULT_HEIGHT;
    fmt.fmt.pix.pixelformat = DEFAULT_PIXEL_FORMAT;
    fmt.fmt.pix.field = V4L2_FIELD_ANY;
    if (ioctl(fd, VIDIOC_S_FMT, &fmt) == -1) {
        perror("Failed to set pixel format");
        goto cleanup;
    }

    // Request a single memory-mapped buffer.
    memset(&req, 0, sizeof(req));
    req.count = 1;
    req.type = V4L2_BUF_TYPE_VIDEO_CAPTURE;
    req.memory = V4L2_MEMORY_MMAP;
    if (ioctl(fd, VIDIOC_REQBUFS, &req) == -1) {
        perror("Failed to request buffers");
        goto cleanup;
    }
    if (req.count < 1) {
        fprintf(stderr, "Insufficient buffer memory\n");
        goto cleanup;
    }

    // Map the buffer.
    memset(&vbuf, 0, sizeof(vbuf));
    vbuf.type = V4L2_BUF_TYPE_VIDEO_CAPTURE;
    vbuf.memory = V4L2_MEMORY_MMAP;
    vbuf.index = 0;
    if (ioctl(fd, VIDIOC_QUERYBUF, &vbuf) == -1) {
        perror("Failed to query buffer");
        goto cleanup;
    }
    frame_buf = mmap(NULL, vbuf.length, PROT_READ | PROT_WRITE, MAP_SHARED, fd, vbuf.m.offset);
    if (frame_buf == MAP_FAILED) {
        perror("Failed to mmap buffer");
        goto cleanup;
    }

    // Queue the buffer.
    if (ioctl(fd, VIDIOC_QBUF, &vbuf) == -1) {
        perror("Failed to queue buffer");
        goto cleanup;
    }

    // Start streaming.
    enum v4l2_buf_type type = V4L2_BUF_TYPE_VIDEO_CAPTURE;
    if (ioctl(fd, VIDIOC_STREAMON, &type) == -1) {
        perror("Failed to start capture stream");
        goto cleanup;
    }

    // Capture one frame (dequeue).
    memset(&vbuf, 0, sizeof(vbuf));
    vbuf.type = V4L2_BUF_TYPE_VIDEO_CAPTURE;
    vbuf.memory = V4L2_MEMORY_MMAP;
    if (ioctl(fd, VIDIOC_DQBUF, &vbuf) == -1) {
        perror("Failed to dequeue buffer");
        goto streamoff;
    }

    // Copy captured data to user buffer (truncate if necessary).
    captured_bytes = (vbuf.bytesused < len) ? vbuf.bytesused : len;
    memcpy(buf, frame_buf, captured_bytes);

streamoff:
    // Stop streaming.
    ioctl(fd, VIDIOC_STREAMOFF, &type);

cleanup:
    if (frame_buf && frame_buf != MAP_FAILED) {
        munmap(frame_buf, vbuf.length);
    }
    close(fd);
    return captured_bytes;
}

