#!/bin/sh -
#
# test_tryrnd - test all of the tryrnd calls
#
# @(#) $Revision: 10.1 $
# @(#) $Id: test_tryrnd,v 10.1 2003/08/18 06:44:37 lavarnd Exp $
#
# Copyright (c) 2000-2003 by Landon Curt Noll and Simon Cooper.
# All Rights Reserved.
#
# This is open software; you can redistribute it and/or modify it under
# the terms of the version 2.1 of the GNU Lesser General Public License
# as published by the Free Software Foundation.
#
# This software is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General
# Public License for more details.
#
# The file COPYING contains important info about Licenses and Copyrights.
# Please read the COPYING file for details about this open software.
#
# A copy of version 2.1 of the GNU Lesser General Public License is
# distributed with calc under the filename COPYING-LGPL.  You should have
# received a copy with calc; if not, write to Free Software Foundation, Inc.
# 59 Temple Place, Suite 330, Boston, MA  02111-1307, USA.
#
# For more information on LavaRnd: http://www.LavaRnd.org
#
# Share and enjoy! :-)

# setup
#
DESTBIN=/usr/bin/lavatool

for i in tryrnd_exit tryrnd_retry tryrnd_return tryrnd_s100_any \
    tryrnd_s100_high tryrnd_s100_med tryrnd_try_any tryrnd_try_high \
    tryrnd_try_med tryrnd_tryonce_any tryrnd_tryonce_high tryrnd_tryonce_med; do

    if [[ -x "./$i" ]]; then
	echo "=-=-= Running ./$i =-=-="
	echo
	./$i
	status="$?"
    elif [ -x "$DESTBIN/$i" ]; then
	echo "=-=-= Running $DESTBIN/$i =-=-="
	echo
    	$DESTBIN/$i
	status="$?"
    else
	echo "$i not found in . or $DESTBIN" 1>&2
	exit 1
    fi
    if [[ "$status" -ne 0 ]]; then
	echo "$i failed, code: $status" 1>&2
	exit 2
    fi
    echo
done
echo "all ok"
exit 0
