#!/bin/sh -
#
# test_perllib - test LavaRnd perl interface
#
# @(#) $Revision: 10.1 $
# @(#) $Id: test_perllib,v 10.1 2003/08/18 06:44:37 lavarnd Exp $
#
# Copyright (c) 2000-2003 by Landon Curt Noll and Simon Cooper.
# All Rights Reserved.
#
# This is open software; you can redistribute it and/or modify it under
# the terms of the version 2.1 of the GNU Lesser General Public License
# as published by the Free Software Foundation.
#
# This software is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General
# Public License for more details.
#
# The file COPYING contains important info about Licenses and Copyrights.
# Please read the COPYING file for details about this open software.
#
# A copy of version 2.1 of the GNU Lesser General Public License is
# distributed with calc under the filename COPYING-LGPL.  You should have
# received a copy with calc; if not, write to Free Software Foundation, Inc.
# 59 Temple Place, Suite 330, Boston, MA  02111-1307, USA.
#
# For more information on LavaRnd: http://www.LavaRnd.org
#
# Share and enjoy! :-)

# test each of the 1.t scrpts under perllib
#
exitcode=0
find ../perllib -name 1.t | while read test; do

    # determine name based on top level directory
    #
    testdir="`dirname $test`"
    testdir="`dirname $testdir`"
    level2="`basename $testdir`"
    testdir="`dirname $testdir`"
    level1="`basename $testdir`"
    echo -n "Testing installed perl module $level1::$level2 - "

    # perl the test
    #
    tmp="/var/tmp/test_perllib.$$"
    trap "rm -f $tmp; exit" 1 2 3 15
    perl "$test" > $tmp 2>&1
    status="$?"
    if [ X"$status" = X"0" ]; then
	echo "sucessful"
    else
	echo "failure code: $status"
	grep -v '^ok' $tmp
	exitcode=$status
    fi
    rm -f $tmp
done

# All done!! -- Jessica Noll, age 2
#
exit $exitcode
