#!/bin/sh -
#
# unload_modules - unload all webcam modules
#
# @(#) $Revision: 10.1 $
# @(#) $Id: unload_modules,v 10.1 2003/08/18 06:44:37 lavarnd Exp $
#
# Copyright (c) 2000-2003 by Landon Curt Noll and Simon Cooper.
# All Rights Reserved.
#
# This is open software; you can redistribute it and/or modify it under
# the terms of the version 2.1 of the GNU Lesser General Public License
# as published by the Free Software Foundation.
#
# This software is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General
# Public License for more details.
#
# A copy of version 2.1 of the GNU Lesser General Public License is
# distributed with calc under the filename COPYING-LGPL.  You should have
# received a copy with calc; if not, write to Free Software Foundation, Inc.
# 59 Temple Place, Suite 330, Boston, MA  02111-1307, USA.
#
# For more information on LavaRnd: http://www.LavaRnd.org
#
# Share and enjoy! :-)

# setup
#
MODULES="pwcx-i386 pwc ov511"

# must be run as root
#
if [[ "`/usr/bin/id -u`" -ne 0 ]]; then
   echo "$0: must be run as root" 1>&2
   exit 1
fi

# remove any potential webcam modules
#
for i in ${MODULES}; do
    echo attemptng to remove the $i module
    /sbin/rmmod -v $i
done

# All Done!!  -- Jessica Noll (Age 2)
#
exit 0
